### ISSUE TITLE
Sistema de Prestamos

### ISSUE THREAD

**Issue by MrDanBar** [software-avanzado/project-one-requirements#1]
Solo con la observación: de que en el enunciado dice que una remesa puede pagar un préstamo, faltaría ese sistema.

**Comment by humbertn** [comment]
Ok, copiado. 

Gracias por el comentario.

**Comment by humbertn** [comment]
Modificado en commit https://github.com/software-avanzado/project-one-requirements/commit/6c515f271882750627d332d3fa765d8ad25c4993
